sudo: false
language: node_js
node_js:
- 9
branches:
  only:
  - master
deploy:
  provider: heroku
  app: chat-testnodejs
  api_key:
    secure: "bYMjp8ypLVcLxF4881R+ux/yxp4KxAk38mJcFlnqPqjXVP1ZyfSJjC45211y9bt6R7VKRrOwUshUViQWTOhcy/CYCl0nbR7yusZBqv5/ooaAkwCodMIsVnutWRwWZcxPLv2168lR+yLen+qjBBvfSjQVOFezZKCQR4RB8aX9UfHo5VHoPYu12iqhbvy7OevgYP4ARSSxZJd+0NmH+TJ68AyEl2lf82icA1dAZmFLJKqfpaQqJaHVDT1plmfPzTHnohaB75Jm3O6L6sa9GTBPY57yQf5V3fBwN0G6gMkwdFB3o9f62RSdd1OFjPpXLup0ZPCCozlSXBcxIsUEjbdCMwstCh8cYYaPcJqJNqw1VVAWIwuv5mkBzDk8Vup7ZmNNXUWgbyn5LOIxCNR5T8FHVxSIg4TzoZS2vlK54Kr+5pcA78IXi7PNwva3+sjPFCfS/kb09F0KherYjuVgBiAWmoIiGngKXRycXZ95747UAPvonzWPPIesCPai6revptZ74f0f+KJD+WjlTM0O6r11mTVM7ynEC2uvZqNtxY0J2vYBeBPdLbWN6mFrJX5RkHlh/2CvFUFczOLWJ9+hjtGLFPW/ivFzuSy7G7vUtgacQL8QEt1eOcGeX6Ae/ujYMD9IDM8zMkdsgcIIRFYeWK/FJ6nj5xQEFW9XkM30BcrmJbE="